### ISSUE TITLE
[Bug]: Failed to sign up

### ISSUE THREAD

**Issue by zhangdongkun98** [Transpile-AI/ivy#28741]
### Bug Explanation

I followed the instructions (https://unify.ai/docs/ivy/overview/get_started.html) to sign up and add the API key to .ivy/key.pem. However, ivy still asks me to sign up.

### Steps to Reproduce Bug

The test code (located at `~/test_ivy.py`) is simple as follows:
```python
import ivy

ivy.trace_graph()
ivy.transpile()
ivy.unify()
```
The API key is at `~/.ivy/key.pem` (ends with '=').

When I run `python test_ivy.py`, an error raises:
```bash
Traceback (most recent call last):
  File "/home/zdk/test_ivy.py", line 4, in <module>
    ivy.trace_graph()
  File "/home/zdk/miniconda3/envs/new_env/lib/python3.10/site-packages/ivy/compiler/compiler.py", line 97, in trace_graph
    from ._compiler import trace_graph as _trace_graph
  File "_compiler.pyx", line 74, in init combined_source._compiler
  File "_compiler.pyx", line 26, in combined_source._compiler
  File "VX.pyx", line 21, in init VX
  File "MC.pyx", line 141, in MC.connect_to_unify
Exception: Please sign up for free pilot access here [https://console.unify.ai/], in order to make use of ivy.trace, ivy.transpile and ivy.unify.
```

I also tried `export IVY_ROOT=~/.ivy`, the error is the same.

### Environment

ubuntu 18.04, python 3.10, ivy 0.0.9.0.

### Ivy Version

0.0.9.0

### Backend

- [x] NumPy
- [x] TensorFlow
- [x] PyTorch
- [x] JAX

**Comment by zhangdongkun98** [comment]
It works! Thanks so much!
